Repository SwiftWeekly/swiftweekly.github.io, pull requests merged in 2018-03, with the labels that each got.

#371 Issue 104
  _drafts/2018-03-08-issue-104.md
  _posts/2018-03-08-issue-104.md
Labels: current issue, full issue notes

#374 Time travel back from future
  _posts/2018-03-08-issue-104.md
Labels: correction

#378 Remove outdated info from Contributing guidelines
  CONTRIBUTING.md
Labels: correction

#377 Add a GitHub issue generator
  CONTRIBUTING.md
  Gemfile
  Gemfile.lock
  github_issue_generator.rb
Labels: enhancement
